### ISSUE TITLE
Crashes for 1.16.4

### ISSUE THREAD

**Issue by willtarax** [Hexeption/RSInfinityBooster#5]
[6ZBgxbP7.txt](https://github.com/Hexeption/RSInfinityBooster/files/6065358/6ZBgxbP7.txt)

I keep being told that my pack needs to be 1.16.5

**Comment by DAmNRelentless** [comment]
Pastebin redirect for the log because nobody wants to download a txt.
https://pastebin.com/9JGLM5KY

The reason is exactly what's written there. The mod is made for 1.16.5. It's build against the 1.16.5 forge mdk. Minecraft won't accept running that mod if you Minecraft version is below the version it's build against or what's set up in the mod's TOML file.

**Comment by willtarax** [comment]
Would it be possible to release a 1.16.4 version?
